<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.6">
  <POU Name="Main" Id="{4fc6a7e2-9479-48b5-85ef-622583cb9cd0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Main
VAR
	dictionary_TestSuite : Dictionary_TestSuite;
	dictionaryForwardEnumerator_TestSuite : DictionaryForwardEnumerator_TestSuite;
	dictionaryKeyValueForwardEnumerator_TestSuite : DictionaryKeyValueForwardEnumerator_TestSuite;
	orderedDictionary_TestSuite : OrderedDictionary_TestSuite;
	orderedDictionaryForwardEnumerator_TestSuite : OrderedDictionaryForwardEnumerator_TestSuite;
	orderedDicKeyValueForwardEnumerator_TestSuite : OrderedDicKeyValueForwardEnumerator_TestSuite;
    linkedList_TestSuite : LinkedList_TestSuite;
	linkedListForwardEnumerator_TestSuite : LinkedListForwardEnumerator_TestSuite;
    list_TestSuite : List_TestSuite;
    listEnumerator_TestSuite : ListForwardEnumerator_TestSuite;
	queue_TestSuite : Queue_TestSuite;
	queueForwardEnumerator_TestSuite : QueueForwardEnumerator_TestSuite;
    stack_TestSuite : Stack_TestSuite;
	stackForwardEnumerator_TestSuite : StackForwardEnumerator_TestSuite;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.Run();
]]></ST>
    </Implementation>
    <LineIds Name="Main">
      <LineId Id="3" Count="0" />
      <LineId Id="99" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>